package com.magicjack.webservice.iristel.dao.mapper;

import com.magicjack.webservice.iristel.domain.vo.CreatePonsRequestRoutingDetail;
import com.magicjack.webservice.iristel.domain.vo.CreatePonsRequestRoutingDetailExample.Criteria;
import com.magicjack.webservice.iristel.domain.vo.CreatePonsRequestRoutingDetailExample.Criterion;
import com.magicjack.webservice.iristel.domain.vo.CreatePonsRequestRoutingDetailExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class CreatePonsRequestRoutingDetailSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CRT_PONS_REQ_ROUTING_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public String countByExample(CreatePonsRequestRoutingDetailExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("\"MSUN\".\"CRT_PONS_REQ_ROUTING_DETAILS\"");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CRT_PONS_REQ_ROUTING_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public String deleteByExample(CreatePonsRequestRoutingDetailExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("\"MSUN\".\"CRT_PONS_REQ_ROUTING_DETAILS\"");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CRT_PONS_REQ_ROUTING_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public String insertSelective(CreatePonsRequestRoutingDetail record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("\"MSUN\".\"CRT_PONS_REQ_ROUTING_DETAILS\"");
        
        if (record.getId() != null) {
            sql.VALUES("\"ID\"", "#{id,jdbcType=DECIMAL}");
        }
        
        if (record.getSeq() != null) {
            sql.VALUES("\"SEQ\"", "#{seq,jdbcType=DECIMAL}");
        }
        
        if (record.getRoutingProfile() != null) {
            sql.VALUES("\"ROUTING_PROFILE\"", "#{routingProfile,jdbcType=CHAR}");
        }
        
        if (record.getStartNumber() != null) {
            sql.VALUES("\"START_NUMBER\"", "#{startNumber,jdbcType=VARCHAR}");
        }
        
        if (record.getEndNumber() != null) {
            sql.VALUES("\"END_NUMBER\"", "#{endNumber,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CRT_PONS_REQ_ROUTING_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public String selectByExample(CreatePonsRequestRoutingDetailExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("\"ID\"");
        } else {
            sql.SELECT("\"ID\"");
        }
        sql.SELECT("\"SEQ\"");
        sql.SELECT("\"ROUTING_PROFILE\"");
        sql.SELECT("\"START_NUMBER\"");
        sql.SELECT("\"END_NUMBER\"");
        sql.FROM("\"MSUN\".\"CRT_PONS_REQ_ROUTING_DETAILS\"");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CRT_PONS_REQ_ROUTING_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CreatePonsRequestRoutingDetail record = (CreatePonsRequestRoutingDetail) parameter.get("record");
        CreatePonsRequestRoutingDetailExample example = (CreatePonsRequestRoutingDetailExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("\"MSUN\".\"CRT_PONS_REQ_ROUTING_DETAILS\"");
        
        if (record.getId() != null) {
            sql.SET("\"ID\" = #{record.id,jdbcType=DECIMAL}");
        }
        
        if (record.getSeq() != null) {
            sql.SET("\"SEQ\" = #{record.seq,jdbcType=DECIMAL}");
        }
        
        if (record.getRoutingProfile() != null) {
            sql.SET("\"ROUTING_PROFILE\" = #{record.routingProfile,jdbcType=CHAR}");
        }
        
        if (record.getStartNumber() != null) {
            sql.SET("\"START_NUMBER\" = #{record.startNumber,jdbcType=VARCHAR}");
        }
        
        if (record.getEndNumber() != null) {
            sql.SET("\"END_NUMBER\" = #{record.endNumber,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CRT_PONS_REQ_ROUTING_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("\"MSUN\".\"CRT_PONS_REQ_ROUTING_DETAILS\"");
        
        sql.SET("\"ID\" = #{record.id,jdbcType=DECIMAL}");
        sql.SET("\"SEQ\" = #{record.seq,jdbcType=DECIMAL}");
        sql.SET("\"ROUTING_PROFILE\" = #{record.routingProfile,jdbcType=CHAR}");
        sql.SET("\"START_NUMBER\" = #{record.startNumber,jdbcType=VARCHAR}");
        sql.SET("\"END_NUMBER\" = #{record.endNumber,jdbcType=VARCHAR}");
        
        CreatePonsRequestRoutingDetailExample example = (CreatePonsRequestRoutingDetailExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CRT_PONS_REQ_ROUTING_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public String updateByPrimaryKeySelective(CreatePonsRequestRoutingDetail record) {
        SQL sql = new SQL();
        sql.UPDATE("\"MSUN\".\"CRT_PONS_REQ_ROUTING_DETAILS\"");
        
        if (record.getRoutingProfile() != null) {
            sql.SET("\"ROUTING_PROFILE\" = #{routingProfile,jdbcType=CHAR}");
        }
        
        if (record.getStartNumber() != null) {
            sql.SET("\"START_NUMBER\" = #{startNumber,jdbcType=VARCHAR}");
        }
        
        if (record.getEndNumber() != null) {
            sql.SET("\"END_NUMBER\" = #{endNumber,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("\"ID\" = #{id,jdbcType=DECIMAL}");
        sql.WHERE("\"SEQ\" = #{seq,jdbcType=DECIMAL}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CRT_PONS_REQ_ROUTING_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    protected void applyWhere(SQL sql, CreatePonsRequestRoutingDetailExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}