package com.magicjack.webservice.iristel.dao.mapper;

import com.magicjack.webservice.iristel.domain.vo.CreatePonsRequestRoutingDetail;
import com.magicjack.webservice.iristel.domain.vo.CreatePonsRequestRoutingDetailExample;
import com.magicjack.webservice.iristel.domain.vo.CreatePonsRequestRoutingDetailKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface CreatePonsRequestRoutingDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CRT_PONS_REQ_ROUTING_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    @SelectProvider(type=CreatePonsRequestRoutingDetailSqlProvider.class, method="countByExample")
    long countByExample(CreatePonsRequestRoutingDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CRT_PONS_REQ_ROUTING_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    @DeleteProvider(type=CreatePonsRequestRoutingDetailSqlProvider.class, method="deleteByExample")
    int deleteByExample(CreatePonsRequestRoutingDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CRT_PONS_REQ_ROUTING_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    @Delete({
        "delete from \"MSUN\".\"CRT_PONS_REQ_ROUTING_DETAILS\"",
        "where \"ID\" = #{id,jdbcType=DECIMAL}",
          "and \"SEQ\" = #{seq,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(CreatePonsRequestRoutingDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CRT_PONS_REQ_ROUTING_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    @Insert({
        "insert into \"MSUN\".\"CRT_PONS_REQ_ROUTING_DETAILS\" (\"ID\", \"SEQ\", ",
        "\"ROUTING_PROFILE\", \"START_NUMBER\", ",
        "\"END_NUMBER\")",
        "values (#{id,jdbcType=DECIMAL}, #{seq,jdbcType=DECIMAL}, ",
        "#{routingProfile,jdbcType=CHAR}, #{startNumber,jdbcType=VARCHAR}, ",
        "#{endNumber,jdbcType=VARCHAR})"
    })
    int insert(CreatePonsRequestRoutingDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CRT_PONS_REQ_ROUTING_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    @InsertProvider(type=CreatePonsRequestRoutingDetailSqlProvider.class, method="insertSelective")
    int insertSelective(CreatePonsRequestRoutingDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CRT_PONS_REQ_ROUTING_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    @SelectProvider(type=CreatePonsRequestRoutingDetailSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="SEQ", property="seq", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="ROUTING_PROFILE", property="routingProfile", jdbcType=JdbcType.CHAR),
        @Result(column="START_NUMBER", property="startNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="END_NUMBER", property="endNumber", jdbcType=JdbcType.VARCHAR)
    })
    List<CreatePonsRequestRoutingDetail> selectByExample(CreatePonsRequestRoutingDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CRT_PONS_REQ_ROUTING_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    @Select({
        "select",
        "\"ID\", \"SEQ\", \"ROUTING_PROFILE\", \"START_NUMBER\", \"END_NUMBER\"",
        "from \"MSUN\".\"CRT_PONS_REQ_ROUTING_DETAILS\"",
        "where \"ID\" = #{id,jdbcType=DECIMAL}",
          "and \"SEQ\" = #{seq,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="SEQ", property="seq", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="ROUTING_PROFILE", property="routingProfile", jdbcType=JdbcType.CHAR),
        @Result(column="START_NUMBER", property="startNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="END_NUMBER", property="endNumber", jdbcType=JdbcType.VARCHAR)
    })
    CreatePonsRequestRoutingDetail selectByPrimaryKey(CreatePonsRequestRoutingDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CRT_PONS_REQ_ROUTING_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    @UpdateProvider(type=CreatePonsRequestRoutingDetailSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CreatePonsRequestRoutingDetail record, @Param("example") CreatePonsRequestRoutingDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CRT_PONS_REQ_ROUTING_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    @UpdateProvider(type=CreatePonsRequestRoutingDetailSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") CreatePonsRequestRoutingDetail record, @Param("example") CreatePonsRequestRoutingDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CRT_PONS_REQ_ROUTING_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    @UpdateProvider(type=CreatePonsRequestRoutingDetailSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CreatePonsRequestRoutingDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CRT_PONS_REQ_ROUTING_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    @Update({
        "update \"MSUN\".\"CRT_PONS_REQ_ROUTING_DETAILS\"",
        "set \"ROUTING_PROFILE\" = #{routingProfile,jdbcType=CHAR},",
          "\"START_NUMBER\" = #{startNumber,jdbcType=VARCHAR},",
          "\"END_NUMBER\" = #{endNumber,jdbcType=VARCHAR}",
        "where \"ID\" = #{id,jdbcType=DECIMAL}",
          "and \"SEQ\" = #{seq,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(CreatePonsRequestRoutingDetail record);
}