package com.magicjack.webservice.iristel.dao.mapper;

import com.magicjack.webservice.iristel.domain.vo.CreatePonsRequest;
import com.magicjack.webservice.iristel.domain.vo.CreatePonsRequestExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface CreatePonsRequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    @SelectProvider(type=CreatePonsRequestSqlProvider.class, method="countByExample")
    long countByExample(CreatePonsRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    @DeleteProvider(type=CreatePonsRequestSqlProvider.class, method="deleteByExample")
    int deleteByExample(CreatePonsRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    @Delete({
        "delete from \"MSUN\".\"CREATE_PONS_REQUEST\"",
        "where \"ID\" = #{id,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    @Insert({
        "insert into \"MSUN\".\"CREATE_PONS_REQUEST\" (\"ID\", \"SERVICE_TYPE\", ",
        "\"CURRENT_PROVIDER_NAME\", \"DESIRED_DUE_DATE\", ",
        "\"AUTH_DATE\", \"END_USER_NAME\", ",
        "\"HOUSE_NUMBER\", \"STREET_DIRECTIONAL\", ",
        "\"STREET_SUFFIX\", \"STREET_NAME\", ",
        "\"STREET_TYPE\", \"DESCRIPTIVE_LOCATION\", ",
        "\"FLOOR\", \"ROOM\", \"BUILDING\", ",
        "\"CITY\", \"PROVINCE_STATE\", ",
        "\"ZIP_CODE\", \"COMMENTS\", ",
        "\"LOSING_CARRIER_COMMENTS\", \"DEFAULT_ROUTING_PROIFLE\", ",
        "\"CREATED_BY\", \"CREATED_TS\")",
        "values (#{id,jdbcType=DECIMAL}, #{serviceType,jdbcType=VARCHAR}, ",
        "#{currentProviderName,jdbcType=VARCHAR}, #{desiredDueDate,jdbcType=VARCHAR}, ",
        "#{authDate,jdbcType=VARCHAR}, #{endUserName,jdbcType=VARCHAR}, ",
        "#{houseNumber,jdbcType=VARCHAR}, #{streetDirectional,jdbcType=VARCHAR}, ",
        "#{streetSuffix,jdbcType=VARCHAR}, #{streetName,jdbcType=VARCHAR}, ",
        "#{streetType,jdbcType=VARCHAR}, #{descriptiveLocation,jdbcType=VARCHAR}, ",
        "#{floor,jdbcType=VARCHAR}, #{room,jdbcType=VARCHAR}, #{building,jdbcType=VARCHAR}, ",
        "#{city,jdbcType=VARCHAR}, #{provinceState,jdbcType=VARCHAR}, ",
        "#{zipCode,jdbcType=VARCHAR}, #{comments,jdbcType=VARCHAR}, ",
        "#{losingCarrierComments,jdbcType=VARCHAR}, #{defaultRoutingProifle,jdbcType=DECIMAL}, ",
        "#{createdBy,jdbcType=VARCHAR}, #{createdTs,jdbcType=TIMESTAMP})"
    })
    int insert(CreatePonsRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    @InsertProvider(type=CreatePonsRequestSqlProvider.class, method="insertSelective")
    int insertSelective(CreatePonsRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    @SelectProvider(type=CreatePonsRequestSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="SERVICE_TYPE", property="serviceType", jdbcType=JdbcType.VARCHAR),
        @Result(column="CURRENT_PROVIDER_NAME", property="currentProviderName", jdbcType=JdbcType.VARCHAR),
        @Result(column="DESIRED_DUE_DATE", property="desiredDueDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="AUTH_DATE", property="authDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="END_USER_NAME", property="endUserName", jdbcType=JdbcType.VARCHAR),
        @Result(column="HOUSE_NUMBER", property="houseNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="STREET_DIRECTIONAL", property="streetDirectional", jdbcType=JdbcType.VARCHAR),
        @Result(column="STREET_SUFFIX", property="streetSuffix", jdbcType=JdbcType.VARCHAR),
        @Result(column="STREET_NAME", property="streetName", jdbcType=JdbcType.VARCHAR),
        @Result(column="STREET_TYPE", property="streetType", jdbcType=JdbcType.VARCHAR),
        @Result(column="DESCRIPTIVE_LOCATION", property="descriptiveLocation", jdbcType=JdbcType.VARCHAR),
        @Result(column="FLOOR", property="floor", jdbcType=JdbcType.VARCHAR),
        @Result(column="ROOM", property="room", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUILDING", property="building", jdbcType=JdbcType.VARCHAR),
        @Result(column="CITY", property="city", jdbcType=JdbcType.VARCHAR),
        @Result(column="PROVINCE_STATE", property="provinceState", jdbcType=JdbcType.VARCHAR),
        @Result(column="ZIP_CODE", property="zipCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="COMMENTS", property="comments", jdbcType=JdbcType.VARCHAR),
        @Result(column="LOSING_CARRIER_COMMENTS", property="losingCarrierComments", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEFAULT_ROUTING_PROIFLE", property="defaultRoutingProifle", jdbcType=JdbcType.DECIMAL),
        @Result(column="CREATED_BY", property="createdBy", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATED_TS", property="createdTs", jdbcType=JdbcType.TIMESTAMP)
    })
    List<CreatePonsRequest> selectByExample(CreatePonsRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    @Select({
        "select",
        "\"ID\", \"SERVICE_TYPE\", \"CURRENT_PROVIDER_NAME\", \"DESIRED_DUE_DATE\", \"AUTH_DATE\", ",
        "\"END_USER_NAME\", \"HOUSE_NUMBER\", \"STREET_DIRECTIONAL\", \"STREET_SUFFIX\", ",
        "\"STREET_NAME\", \"STREET_TYPE\", \"DESCRIPTIVE_LOCATION\", \"FLOOR\", \"ROOM\", ",
        "\"BUILDING\", \"CITY\", \"PROVINCE_STATE\", \"ZIP_CODE\", \"COMMENTS\", \"LOSING_CARRIER_COMMENTS\", ",
        "\"DEFAULT_ROUTING_PROIFLE\", \"CREATED_BY\", \"CREATED_TS\"",
        "from \"MSUN\".\"CREATE_PONS_REQUEST\"",
        "where \"ID\" = #{id,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="SERVICE_TYPE", property="serviceType", jdbcType=JdbcType.VARCHAR),
        @Result(column="CURRENT_PROVIDER_NAME", property="currentProviderName", jdbcType=JdbcType.VARCHAR),
        @Result(column="DESIRED_DUE_DATE", property="desiredDueDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="AUTH_DATE", property="authDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="END_USER_NAME", property="endUserName", jdbcType=JdbcType.VARCHAR),
        @Result(column="HOUSE_NUMBER", property="houseNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="STREET_DIRECTIONAL", property="streetDirectional", jdbcType=JdbcType.VARCHAR),
        @Result(column="STREET_SUFFIX", property="streetSuffix", jdbcType=JdbcType.VARCHAR),
        @Result(column="STREET_NAME", property="streetName", jdbcType=JdbcType.VARCHAR),
        @Result(column="STREET_TYPE", property="streetType", jdbcType=JdbcType.VARCHAR),
        @Result(column="DESCRIPTIVE_LOCATION", property="descriptiveLocation", jdbcType=JdbcType.VARCHAR),
        @Result(column="FLOOR", property="floor", jdbcType=JdbcType.VARCHAR),
        @Result(column="ROOM", property="room", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUILDING", property="building", jdbcType=JdbcType.VARCHAR),
        @Result(column="CITY", property="city", jdbcType=JdbcType.VARCHAR),
        @Result(column="PROVINCE_STATE", property="provinceState", jdbcType=JdbcType.VARCHAR),
        @Result(column="ZIP_CODE", property="zipCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="COMMENTS", property="comments", jdbcType=JdbcType.VARCHAR),
        @Result(column="LOSING_CARRIER_COMMENTS", property="losingCarrierComments", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEFAULT_ROUTING_PROIFLE", property="defaultRoutingProifle", jdbcType=JdbcType.DECIMAL),
        @Result(column="CREATED_BY", property="createdBy", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATED_TS", property="createdTs", jdbcType=JdbcType.TIMESTAMP)
    })
    CreatePonsRequest selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    @UpdateProvider(type=CreatePonsRequestSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CreatePonsRequest record, @Param("example") CreatePonsRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    @UpdateProvider(type=CreatePonsRequestSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") CreatePonsRequest record, @Param("example") CreatePonsRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    @UpdateProvider(type=CreatePonsRequestSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CreatePonsRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    @Update({
        "update \"MSUN\".\"CREATE_PONS_REQUEST\"",
        "set \"SERVICE_TYPE\" = #{serviceType,jdbcType=VARCHAR},",
          "\"CURRENT_PROVIDER_NAME\" = #{currentProviderName,jdbcType=VARCHAR},",
          "\"DESIRED_DUE_DATE\" = #{desiredDueDate,jdbcType=VARCHAR},",
          "\"AUTH_DATE\" = #{authDate,jdbcType=VARCHAR},",
          "\"END_USER_NAME\" = #{endUserName,jdbcType=VARCHAR},",
          "\"HOUSE_NUMBER\" = #{houseNumber,jdbcType=VARCHAR},",
          "\"STREET_DIRECTIONAL\" = #{streetDirectional,jdbcType=VARCHAR},",
          "\"STREET_SUFFIX\" = #{streetSuffix,jdbcType=VARCHAR},",
          "\"STREET_NAME\" = #{streetName,jdbcType=VARCHAR},",
          "\"STREET_TYPE\" = #{streetType,jdbcType=VARCHAR},",
          "\"DESCRIPTIVE_LOCATION\" = #{descriptiveLocation,jdbcType=VARCHAR},",
          "\"FLOOR\" = #{floor,jdbcType=VARCHAR},",
          "\"ROOM\" = #{room,jdbcType=VARCHAR},",
          "\"BUILDING\" = #{building,jdbcType=VARCHAR},",
          "\"CITY\" = #{city,jdbcType=VARCHAR},",
          "\"PROVINCE_STATE\" = #{provinceState,jdbcType=VARCHAR},",
          "\"ZIP_CODE\" = #{zipCode,jdbcType=VARCHAR},",
          "\"COMMENTS\" = #{comments,jdbcType=VARCHAR},",
          "\"LOSING_CARRIER_COMMENTS\" = #{losingCarrierComments,jdbcType=VARCHAR},",
          "\"DEFAULT_ROUTING_PROIFLE\" = #{defaultRoutingProifle,jdbcType=DECIMAL},",
          "\"CREATED_BY\" = #{createdBy,jdbcType=VARCHAR},",
          "\"CREATED_TS\" = #{createdTs,jdbcType=TIMESTAMP}",
        "where \"ID\" = #{id,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(CreatePonsRequest record);
}