package com.magicjack.webservice.iristel.domain.vo;

public class CreatePonsRequestRoutingDetail extends CreatePonsRequestRoutingDetailKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CRT_PONS_REQ_ROUTING_DETAILS.ROUTING_PROFILE
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    private String routingProfile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CRT_PONS_REQ_ROUTING_DETAILS.START_NUMBER
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    private String startNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CRT_PONS_REQ_ROUTING_DETAILS.END_NUMBER
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    private String endNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CRT_PONS_REQ_ROUTING_DETAILS.ROUTING_PROFILE
     *
     * @return the value of MSUN.CRT_PONS_REQ_ROUTING_DETAILS.ROUTING_PROFILE
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public String getRoutingProfile() {
        return routingProfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CRT_PONS_REQ_ROUTING_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public CreatePonsRequestRoutingDetail withRoutingProfile(String routingProfile) {
        this.setRoutingProfile(routingProfile);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CRT_PONS_REQ_ROUTING_DETAILS.ROUTING_PROFILE
     *
     * @param routingProfile the value for MSUN.CRT_PONS_REQ_ROUTING_DETAILS.ROUTING_PROFILE
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public void setRoutingProfile(String routingProfile) {
        this.routingProfile = routingProfile == null ? null : routingProfile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CRT_PONS_REQ_ROUTING_DETAILS.START_NUMBER
     *
     * @return the value of MSUN.CRT_PONS_REQ_ROUTING_DETAILS.START_NUMBER
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public String getStartNumber() {
        return startNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CRT_PONS_REQ_ROUTING_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public CreatePonsRequestRoutingDetail withStartNumber(String startNumber) {
        this.setStartNumber(startNumber);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CRT_PONS_REQ_ROUTING_DETAILS.START_NUMBER
     *
     * @param startNumber the value for MSUN.CRT_PONS_REQ_ROUTING_DETAILS.START_NUMBER
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public void setStartNumber(String startNumber) {
        this.startNumber = startNumber == null ? null : startNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CRT_PONS_REQ_ROUTING_DETAILS.END_NUMBER
     *
     * @return the value of MSUN.CRT_PONS_REQ_ROUTING_DETAILS.END_NUMBER
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public String getEndNumber() {
        return endNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CRT_PONS_REQ_ROUTING_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public CreatePonsRequestRoutingDetail withEndNumber(String endNumber) {
        this.setEndNumber(endNumber);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CRT_PONS_REQ_ROUTING_DETAILS.END_NUMBER
     *
     * @param endNumber the value for MSUN.CRT_PONS_REQ_ROUTING_DETAILS.END_NUMBER
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public void setEndNumber(String endNumber) {
        this.endNumber = endNumber == null ? null : endNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CRT_PONS_REQ_ROUTING_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", routingProfile=").append(routingProfile);
        sb.append(", startNumber=").append(startNumber);
        sb.append(", endNumber=").append(endNumber);
        sb.append("]");
        return sb.toString();
    }
}