package com.magicjack.webservice.iristel.domain.vo;

import java.util.Date;

public class CreatePonsRequest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQUEST.ID
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQUEST.SERVICE_TYPE
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    private String serviceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQUEST.CURRENT_PROVIDER_NAME
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    private String currentProviderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQUEST.DESIRED_DUE_DATE
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    private String desiredDueDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQUEST.AUTH_DATE
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    private String authDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQUEST.END_USER_NAME
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    private String endUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQUEST.HOUSE_NUMBER
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    private String houseNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQUEST.STREET_DIRECTIONAL
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    private String streetDirectional;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQUEST.STREET_SUFFIX
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    private String streetSuffix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQUEST.STREET_NAME
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    private String streetName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQUEST.STREET_TYPE
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    private String streetType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQUEST.DESCRIPTIVE_LOCATION
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    private String descriptiveLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQUEST.FLOOR
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    private String floor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQUEST.ROOM
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    private String room;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQUEST.BUILDING
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    private String building;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQUEST.CITY
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQUEST.PROVINCE_STATE
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    private String provinceState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQUEST.ZIP_CODE
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    private String zipCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQUEST.COMMENTS
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    private String comments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQUEST.LOSING_CARRIER_COMMENTS
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    private String losingCarrierComments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQUEST.DEFAULT_ROUTING_PROIFLE
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    private Integer defaultRoutingProifle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQUEST.CREATED_BY
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQUEST.CREATED_TS
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    private Date createdTs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQUEST.ID
     *
     * @return the value of MSUN.CREATE_PONS_REQUEST.ID
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public CreatePonsRequest withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQUEST.ID
     *
     * @param id the value for MSUN.CREATE_PONS_REQUEST.ID
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQUEST.SERVICE_TYPE
     *
     * @return the value of MSUN.CREATE_PONS_REQUEST.SERVICE_TYPE
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public CreatePonsRequest withServiceType(String serviceType) {
        this.setServiceType(serviceType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQUEST.SERVICE_TYPE
     *
     * @param serviceType the value for MSUN.CREATE_PONS_REQUEST.SERVICE_TYPE
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public void setServiceType(String serviceType) {
        this.serviceType = serviceType == null ? null : serviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQUEST.CURRENT_PROVIDER_NAME
     *
     * @return the value of MSUN.CREATE_PONS_REQUEST.CURRENT_PROVIDER_NAME
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public String getCurrentProviderName() {
        return currentProviderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public CreatePonsRequest withCurrentProviderName(String currentProviderName) {
        this.setCurrentProviderName(currentProviderName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQUEST.CURRENT_PROVIDER_NAME
     *
     * @param currentProviderName the value for MSUN.CREATE_PONS_REQUEST.CURRENT_PROVIDER_NAME
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public void setCurrentProviderName(String currentProviderName) {
        this.currentProviderName = currentProviderName == null ? null : currentProviderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQUEST.DESIRED_DUE_DATE
     *
     * @return the value of MSUN.CREATE_PONS_REQUEST.DESIRED_DUE_DATE
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public String getDesiredDueDate() {
        return desiredDueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public CreatePonsRequest withDesiredDueDate(String desiredDueDate) {
        this.setDesiredDueDate(desiredDueDate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQUEST.DESIRED_DUE_DATE
     *
     * @param desiredDueDate the value for MSUN.CREATE_PONS_REQUEST.DESIRED_DUE_DATE
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public void setDesiredDueDate(String desiredDueDate) {
        this.desiredDueDate = desiredDueDate == null ? null : desiredDueDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQUEST.AUTH_DATE
     *
     * @return the value of MSUN.CREATE_PONS_REQUEST.AUTH_DATE
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public String getAuthDate() {
        return authDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public CreatePonsRequest withAuthDate(String authDate) {
        this.setAuthDate(authDate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQUEST.AUTH_DATE
     *
     * @param authDate the value for MSUN.CREATE_PONS_REQUEST.AUTH_DATE
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public void setAuthDate(String authDate) {
        this.authDate = authDate == null ? null : authDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQUEST.END_USER_NAME
     *
     * @return the value of MSUN.CREATE_PONS_REQUEST.END_USER_NAME
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public String getEndUserName() {
        return endUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public CreatePonsRequest withEndUserName(String endUserName) {
        this.setEndUserName(endUserName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQUEST.END_USER_NAME
     *
     * @param endUserName the value for MSUN.CREATE_PONS_REQUEST.END_USER_NAME
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public void setEndUserName(String endUserName) {
        this.endUserName = endUserName == null ? null : endUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQUEST.HOUSE_NUMBER
     *
     * @return the value of MSUN.CREATE_PONS_REQUEST.HOUSE_NUMBER
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public String getHouseNumber() {
        return houseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public CreatePonsRequest withHouseNumber(String houseNumber) {
        this.setHouseNumber(houseNumber);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQUEST.HOUSE_NUMBER
     *
     * @param houseNumber the value for MSUN.CREATE_PONS_REQUEST.HOUSE_NUMBER
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public void setHouseNumber(String houseNumber) {
        this.houseNumber = houseNumber == null ? null : houseNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQUEST.STREET_DIRECTIONAL
     *
     * @return the value of MSUN.CREATE_PONS_REQUEST.STREET_DIRECTIONAL
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public String getStreetDirectional() {
        return streetDirectional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public CreatePonsRequest withStreetDirectional(String streetDirectional) {
        this.setStreetDirectional(streetDirectional);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQUEST.STREET_DIRECTIONAL
     *
     * @param streetDirectional the value for MSUN.CREATE_PONS_REQUEST.STREET_DIRECTIONAL
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public void setStreetDirectional(String streetDirectional) {
        this.streetDirectional = streetDirectional == null ? null : streetDirectional.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQUEST.STREET_SUFFIX
     *
     * @return the value of MSUN.CREATE_PONS_REQUEST.STREET_SUFFIX
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public String getStreetSuffix() {
        return streetSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public CreatePonsRequest withStreetSuffix(String streetSuffix) {
        this.setStreetSuffix(streetSuffix);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQUEST.STREET_SUFFIX
     *
     * @param streetSuffix the value for MSUN.CREATE_PONS_REQUEST.STREET_SUFFIX
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public void setStreetSuffix(String streetSuffix) {
        this.streetSuffix = streetSuffix == null ? null : streetSuffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQUEST.STREET_NAME
     *
     * @return the value of MSUN.CREATE_PONS_REQUEST.STREET_NAME
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public String getStreetName() {
        return streetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public CreatePonsRequest withStreetName(String streetName) {
        this.setStreetName(streetName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQUEST.STREET_NAME
     *
     * @param streetName the value for MSUN.CREATE_PONS_REQUEST.STREET_NAME
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public void setStreetName(String streetName) {
        this.streetName = streetName == null ? null : streetName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQUEST.STREET_TYPE
     *
     * @return the value of MSUN.CREATE_PONS_REQUEST.STREET_TYPE
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public String getStreetType() {
        return streetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public CreatePonsRequest withStreetType(String streetType) {
        this.setStreetType(streetType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQUEST.STREET_TYPE
     *
     * @param streetType the value for MSUN.CREATE_PONS_REQUEST.STREET_TYPE
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public void setStreetType(String streetType) {
        this.streetType = streetType == null ? null : streetType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQUEST.DESCRIPTIVE_LOCATION
     *
     * @return the value of MSUN.CREATE_PONS_REQUEST.DESCRIPTIVE_LOCATION
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public String getDescriptiveLocation() {
        return descriptiveLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public CreatePonsRequest withDescriptiveLocation(String descriptiveLocation) {
        this.setDescriptiveLocation(descriptiveLocation);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQUEST.DESCRIPTIVE_LOCATION
     *
     * @param descriptiveLocation the value for MSUN.CREATE_PONS_REQUEST.DESCRIPTIVE_LOCATION
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public void setDescriptiveLocation(String descriptiveLocation) {
        this.descriptiveLocation = descriptiveLocation == null ? null : descriptiveLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQUEST.FLOOR
     *
     * @return the value of MSUN.CREATE_PONS_REQUEST.FLOOR
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public String getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public CreatePonsRequest withFloor(String floor) {
        this.setFloor(floor);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQUEST.FLOOR
     *
     * @param floor the value for MSUN.CREATE_PONS_REQUEST.FLOOR
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public void setFloor(String floor) {
        this.floor = floor == null ? null : floor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQUEST.ROOM
     *
     * @return the value of MSUN.CREATE_PONS_REQUEST.ROOM
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public String getRoom() {
        return room;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public CreatePonsRequest withRoom(String room) {
        this.setRoom(room);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQUEST.ROOM
     *
     * @param room the value for MSUN.CREATE_PONS_REQUEST.ROOM
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public void setRoom(String room) {
        this.room = room == null ? null : room.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQUEST.BUILDING
     *
     * @return the value of MSUN.CREATE_PONS_REQUEST.BUILDING
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public String getBuilding() {
        return building;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public CreatePonsRequest withBuilding(String building) {
        this.setBuilding(building);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQUEST.BUILDING
     *
     * @param building the value for MSUN.CREATE_PONS_REQUEST.BUILDING
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public void setBuilding(String building) {
        this.building = building == null ? null : building.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQUEST.CITY
     *
     * @return the value of MSUN.CREATE_PONS_REQUEST.CITY
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public CreatePonsRequest withCity(String city) {
        this.setCity(city);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQUEST.CITY
     *
     * @param city the value for MSUN.CREATE_PONS_REQUEST.CITY
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQUEST.PROVINCE_STATE
     *
     * @return the value of MSUN.CREATE_PONS_REQUEST.PROVINCE_STATE
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public String getProvinceState() {
        return provinceState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public CreatePonsRequest withProvinceState(String provinceState) {
        this.setProvinceState(provinceState);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQUEST.PROVINCE_STATE
     *
     * @param provinceState the value for MSUN.CREATE_PONS_REQUEST.PROVINCE_STATE
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public void setProvinceState(String provinceState) {
        this.provinceState = provinceState == null ? null : provinceState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQUEST.ZIP_CODE
     *
     * @return the value of MSUN.CREATE_PONS_REQUEST.ZIP_CODE
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public CreatePonsRequest withZipCode(String zipCode) {
        this.setZipCode(zipCode);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQUEST.ZIP_CODE
     *
     * @param zipCode the value for MSUN.CREATE_PONS_REQUEST.ZIP_CODE
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQUEST.COMMENTS
     *
     * @return the value of MSUN.CREATE_PONS_REQUEST.COMMENTS
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public CreatePonsRequest withComments(String comments) {
        this.setComments(comments);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQUEST.COMMENTS
     *
     * @param comments the value for MSUN.CREATE_PONS_REQUEST.COMMENTS
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQUEST.LOSING_CARRIER_COMMENTS
     *
     * @return the value of MSUN.CREATE_PONS_REQUEST.LOSING_CARRIER_COMMENTS
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public String getLosingCarrierComments() {
        return losingCarrierComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public CreatePonsRequest withLosingCarrierComments(String losingCarrierComments) {
        this.setLosingCarrierComments(losingCarrierComments);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQUEST.LOSING_CARRIER_COMMENTS
     *
     * @param losingCarrierComments the value for MSUN.CREATE_PONS_REQUEST.LOSING_CARRIER_COMMENTS
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public void setLosingCarrierComments(String losingCarrierComments) {
        this.losingCarrierComments = losingCarrierComments == null ? null : losingCarrierComments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQUEST.DEFAULT_ROUTING_PROIFLE
     *
     * @return the value of MSUN.CREATE_PONS_REQUEST.DEFAULT_ROUTING_PROIFLE
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public Integer getDefaultRoutingProifle() {
        return defaultRoutingProifle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public CreatePonsRequest withDefaultRoutingProifle(Integer defaultRoutingProifle) {
        this.setDefaultRoutingProifle(defaultRoutingProifle);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQUEST.DEFAULT_ROUTING_PROIFLE
     *
     * @param defaultRoutingProifle the value for MSUN.CREATE_PONS_REQUEST.DEFAULT_ROUTING_PROIFLE
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public void setDefaultRoutingProifle(Integer defaultRoutingProifle) {
        this.defaultRoutingProifle = defaultRoutingProifle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQUEST.CREATED_BY
     *
     * @return the value of MSUN.CREATE_PONS_REQUEST.CREATED_BY
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public CreatePonsRequest withCreatedBy(String createdBy) {
        this.setCreatedBy(createdBy);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQUEST.CREATED_BY
     *
     * @param createdBy the value for MSUN.CREATE_PONS_REQUEST.CREATED_BY
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQUEST.CREATED_TS
     *
     * @return the value of MSUN.CREATE_PONS_REQUEST.CREATED_TS
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public Date getCreatedTs() {
        return createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public CreatePonsRequest withCreatedTs(Date createdTs) {
        this.setCreatedTs(createdTs);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQUEST.CREATED_TS
     *
     * @param createdTs the value for MSUN.CREATE_PONS_REQUEST.CREATED_TS
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public void setCreatedTs(Date createdTs) {
        this.createdTs = createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", serviceType=").append(serviceType);
        sb.append(", currentProviderName=").append(currentProviderName);
        sb.append(", desiredDueDate=").append(desiredDueDate);
        sb.append(", authDate=").append(authDate);
        sb.append(", endUserName=").append(endUserName);
        sb.append(", houseNumber=").append(houseNumber);
        sb.append(", streetDirectional=").append(streetDirectional);
        sb.append(", streetSuffix=").append(streetSuffix);
        sb.append(", streetName=").append(streetName);
        sb.append(", streetType=").append(streetType);
        sb.append(", descriptiveLocation=").append(descriptiveLocation);
        sb.append(", floor=").append(floor);
        sb.append(", room=").append(room);
        sb.append(", building=").append(building);
        sb.append(", city=").append(city);
        sb.append(", provinceState=").append(provinceState);
        sb.append(", zipCode=").append(zipCode);
        sb.append(", comments=").append(comments);
        sb.append(", losingCarrierComments=").append(losingCarrierComments);
        sb.append(", defaultRoutingProifle=").append(defaultRoutingProifle);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", createdTs=").append(createdTs);
        sb.append("]");
        return sb.toString();
    }
}