package com.magicjack.webservice.iristel.domain.vo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CreatePonsRequestExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public CreatePonsRequestExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("\"ID\" is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("\"ID\" is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("\"ID\" =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("\"ID\" <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("\"ID\" >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("\"ID\" >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("\"ID\" <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("\"ID\" <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("\"ID\" in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("\"ID\" not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("\"ID\" between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("\"ID\" not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andServiceTypeIsNull() {
            addCriterion("\"SERVICE_TYPE\" is null");
            return (Criteria) this;
        }

        public Criteria andServiceTypeIsNotNull() {
            addCriterion("\"SERVICE_TYPE\" is not null");
            return (Criteria) this;
        }

        public Criteria andServiceTypeEqualTo(String value) {
            addCriterion("\"SERVICE_TYPE\" =", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeNotEqualTo(String value) {
            addCriterion("\"SERVICE_TYPE\" <>", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeGreaterThan(String value) {
            addCriterion("\"SERVICE_TYPE\" >", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeGreaterThanOrEqualTo(String value) {
            addCriterion("\"SERVICE_TYPE\" >=", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeLessThan(String value) {
            addCriterion("\"SERVICE_TYPE\" <", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeLessThanOrEqualTo(String value) {
            addCriterion("\"SERVICE_TYPE\" <=", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeLike(String value) {
            addCriterion("\"SERVICE_TYPE\" like", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeNotLike(String value) {
            addCriterion("\"SERVICE_TYPE\" not like", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeIn(List<String> values) {
            addCriterion("\"SERVICE_TYPE\" in", values, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeNotIn(List<String> values) {
            addCriterion("\"SERVICE_TYPE\" not in", values, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeBetween(String value1, String value2) {
            addCriterion("\"SERVICE_TYPE\" between", value1, value2, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeNotBetween(String value1, String value2) {
            addCriterion("\"SERVICE_TYPE\" not between", value1, value2, "serviceType");
            return (Criteria) this;
        }

        public Criteria andCurrentProviderNameIsNull() {
            addCriterion("\"CURRENT_PROVIDER_NAME\" is null");
            return (Criteria) this;
        }

        public Criteria andCurrentProviderNameIsNotNull() {
            addCriterion("\"CURRENT_PROVIDER_NAME\" is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentProviderNameEqualTo(String value) {
            addCriterion("\"CURRENT_PROVIDER_NAME\" =", value, "currentProviderName");
            return (Criteria) this;
        }

        public Criteria andCurrentProviderNameNotEqualTo(String value) {
            addCriterion("\"CURRENT_PROVIDER_NAME\" <>", value, "currentProviderName");
            return (Criteria) this;
        }

        public Criteria andCurrentProviderNameGreaterThan(String value) {
            addCriterion("\"CURRENT_PROVIDER_NAME\" >", value, "currentProviderName");
            return (Criteria) this;
        }

        public Criteria andCurrentProviderNameGreaterThanOrEqualTo(String value) {
            addCriterion("\"CURRENT_PROVIDER_NAME\" >=", value, "currentProviderName");
            return (Criteria) this;
        }

        public Criteria andCurrentProviderNameLessThan(String value) {
            addCriterion("\"CURRENT_PROVIDER_NAME\" <", value, "currentProviderName");
            return (Criteria) this;
        }

        public Criteria andCurrentProviderNameLessThanOrEqualTo(String value) {
            addCriterion("\"CURRENT_PROVIDER_NAME\" <=", value, "currentProviderName");
            return (Criteria) this;
        }

        public Criteria andCurrentProviderNameLike(String value) {
            addCriterion("\"CURRENT_PROVIDER_NAME\" like", value, "currentProviderName");
            return (Criteria) this;
        }

        public Criteria andCurrentProviderNameNotLike(String value) {
            addCriterion("\"CURRENT_PROVIDER_NAME\" not like", value, "currentProviderName");
            return (Criteria) this;
        }

        public Criteria andCurrentProviderNameIn(List<String> values) {
            addCriterion("\"CURRENT_PROVIDER_NAME\" in", values, "currentProviderName");
            return (Criteria) this;
        }

        public Criteria andCurrentProviderNameNotIn(List<String> values) {
            addCriterion("\"CURRENT_PROVIDER_NAME\" not in", values, "currentProviderName");
            return (Criteria) this;
        }

        public Criteria andCurrentProviderNameBetween(String value1, String value2) {
            addCriterion("\"CURRENT_PROVIDER_NAME\" between", value1, value2, "currentProviderName");
            return (Criteria) this;
        }

        public Criteria andCurrentProviderNameNotBetween(String value1, String value2) {
            addCriterion("\"CURRENT_PROVIDER_NAME\" not between", value1, value2, "currentProviderName");
            return (Criteria) this;
        }

        public Criteria andDesiredDueDateIsNull() {
            addCriterion("\"DESIRED_DUE_DATE\" is null");
            return (Criteria) this;
        }

        public Criteria andDesiredDueDateIsNotNull() {
            addCriterion("\"DESIRED_DUE_DATE\" is not null");
            return (Criteria) this;
        }

        public Criteria andDesiredDueDateEqualTo(String value) {
            addCriterion("\"DESIRED_DUE_DATE\" =", value, "desiredDueDate");
            return (Criteria) this;
        }

        public Criteria andDesiredDueDateNotEqualTo(String value) {
            addCriterion("\"DESIRED_DUE_DATE\" <>", value, "desiredDueDate");
            return (Criteria) this;
        }

        public Criteria andDesiredDueDateGreaterThan(String value) {
            addCriterion("\"DESIRED_DUE_DATE\" >", value, "desiredDueDate");
            return (Criteria) this;
        }

        public Criteria andDesiredDueDateGreaterThanOrEqualTo(String value) {
            addCriterion("\"DESIRED_DUE_DATE\" >=", value, "desiredDueDate");
            return (Criteria) this;
        }

        public Criteria andDesiredDueDateLessThan(String value) {
            addCriterion("\"DESIRED_DUE_DATE\" <", value, "desiredDueDate");
            return (Criteria) this;
        }

        public Criteria andDesiredDueDateLessThanOrEqualTo(String value) {
            addCriterion("\"DESIRED_DUE_DATE\" <=", value, "desiredDueDate");
            return (Criteria) this;
        }

        public Criteria andDesiredDueDateLike(String value) {
            addCriterion("\"DESIRED_DUE_DATE\" like", value, "desiredDueDate");
            return (Criteria) this;
        }

        public Criteria andDesiredDueDateNotLike(String value) {
            addCriterion("\"DESIRED_DUE_DATE\" not like", value, "desiredDueDate");
            return (Criteria) this;
        }

        public Criteria andDesiredDueDateIn(List<String> values) {
            addCriterion("\"DESIRED_DUE_DATE\" in", values, "desiredDueDate");
            return (Criteria) this;
        }

        public Criteria andDesiredDueDateNotIn(List<String> values) {
            addCriterion("\"DESIRED_DUE_DATE\" not in", values, "desiredDueDate");
            return (Criteria) this;
        }

        public Criteria andDesiredDueDateBetween(String value1, String value2) {
            addCriterion("\"DESIRED_DUE_DATE\" between", value1, value2, "desiredDueDate");
            return (Criteria) this;
        }

        public Criteria andDesiredDueDateNotBetween(String value1, String value2) {
            addCriterion("\"DESIRED_DUE_DATE\" not between", value1, value2, "desiredDueDate");
            return (Criteria) this;
        }

        public Criteria andAuthDateIsNull() {
            addCriterion("\"AUTH_DATE\" is null");
            return (Criteria) this;
        }

        public Criteria andAuthDateIsNotNull() {
            addCriterion("\"AUTH_DATE\" is not null");
            return (Criteria) this;
        }

        public Criteria andAuthDateEqualTo(String value) {
            addCriterion("\"AUTH_DATE\" =", value, "authDate");
            return (Criteria) this;
        }

        public Criteria andAuthDateNotEqualTo(String value) {
            addCriterion("\"AUTH_DATE\" <>", value, "authDate");
            return (Criteria) this;
        }

        public Criteria andAuthDateGreaterThan(String value) {
            addCriterion("\"AUTH_DATE\" >", value, "authDate");
            return (Criteria) this;
        }

        public Criteria andAuthDateGreaterThanOrEqualTo(String value) {
            addCriterion("\"AUTH_DATE\" >=", value, "authDate");
            return (Criteria) this;
        }

        public Criteria andAuthDateLessThan(String value) {
            addCriterion("\"AUTH_DATE\" <", value, "authDate");
            return (Criteria) this;
        }

        public Criteria andAuthDateLessThanOrEqualTo(String value) {
            addCriterion("\"AUTH_DATE\" <=", value, "authDate");
            return (Criteria) this;
        }

        public Criteria andAuthDateLike(String value) {
            addCriterion("\"AUTH_DATE\" like", value, "authDate");
            return (Criteria) this;
        }

        public Criteria andAuthDateNotLike(String value) {
            addCriterion("\"AUTH_DATE\" not like", value, "authDate");
            return (Criteria) this;
        }

        public Criteria andAuthDateIn(List<String> values) {
            addCriterion("\"AUTH_DATE\" in", values, "authDate");
            return (Criteria) this;
        }

        public Criteria andAuthDateNotIn(List<String> values) {
            addCriterion("\"AUTH_DATE\" not in", values, "authDate");
            return (Criteria) this;
        }

        public Criteria andAuthDateBetween(String value1, String value2) {
            addCriterion("\"AUTH_DATE\" between", value1, value2, "authDate");
            return (Criteria) this;
        }

        public Criteria andAuthDateNotBetween(String value1, String value2) {
            addCriterion("\"AUTH_DATE\" not between", value1, value2, "authDate");
            return (Criteria) this;
        }

        public Criteria andEndUserNameIsNull() {
            addCriterion("\"END_USER_NAME\" is null");
            return (Criteria) this;
        }

        public Criteria andEndUserNameIsNotNull() {
            addCriterion("\"END_USER_NAME\" is not null");
            return (Criteria) this;
        }

        public Criteria andEndUserNameEqualTo(String value) {
            addCriterion("\"END_USER_NAME\" =", value, "endUserName");
            return (Criteria) this;
        }

        public Criteria andEndUserNameNotEqualTo(String value) {
            addCriterion("\"END_USER_NAME\" <>", value, "endUserName");
            return (Criteria) this;
        }

        public Criteria andEndUserNameGreaterThan(String value) {
            addCriterion("\"END_USER_NAME\" >", value, "endUserName");
            return (Criteria) this;
        }

        public Criteria andEndUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("\"END_USER_NAME\" >=", value, "endUserName");
            return (Criteria) this;
        }

        public Criteria andEndUserNameLessThan(String value) {
            addCriterion("\"END_USER_NAME\" <", value, "endUserName");
            return (Criteria) this;
        }

        public Criteria andEndUserNameLessThanOrEqualTo(String value) {
            addCriterion("\"END_USER_NAME\" <=", value, "endUserName");
            return (Criteria) this;
        }

        public Criteria andEndUserNameLike(String value) {
            addCriterion("\"END_USER_NAME\" like", value, "endUserName");
            return (Criteria) this;
        }

        public Criteria andEndUserNameNotLike(String value) {
            addCriterion("\"END_USER_NAME\" not like", value, "endUserName");
            return (Criteria) this;
        }

        public Criteria andEndUserNameIn(List<String> values) {
            addCriterion("\"END_USER_NAME\" in", values, "endUserName");
            return (Criteria) this;
        }

        public Criteria andEndUserNameNotIn(List<String> values) {
            addCriterion("\"END_USER_NAME\" not in", values, "endUserName");
            return (Criteria) this;
        }

        public Criteria andEndUserNameBetween(String value1, String value2) {
            addCriterion("\"END_USER_NAME\" between", value1, value2, "endUserName");
            return (Criteria) this;
        }

        public Criteria andEndUserNameNotBetween(String value1, String value2) {
            addCriterion("\"END_USER_NAME\" not between", value1, value2, "endUserName");
            return (Criteria) this;
        }

        public Criteria andHouseNumberIsNull() {
            addCriterion("\"HOUSE_NUMBER\" is null");
            return (Criteria) this;
        }

        public Criteria andHouseNumberIsNotNull() {
            addCriterion("\"HOUSE_NUMBER\" is not null");
            return (Criteria) this;
        }

        public Criteria andHouseNumberEqualTo(String value) {
            addCriterion("\"HOUSE_NUMBER\" =", value, "houseNumber");
            return (Criteria) this;
        }

        public Criteria andHouseNumberNotEqualTo(String value) {
            addCriterion("\"HOUSE_NUMBER\" <>", value, "houseNumber");
            return (Criteria) this;
        }

        public Criteria andHouseNumberGreaterThan(String value) {
            addCriterion("\"HOUSE_NUMBER\" >", value, "houseNumber");
            return (Criteria) this;
        }

        public Criteria andHouseNumberGreaterThanOrEqualTo(String value) {
            addCriterion("\"HOUSE_NUMBER\" >=", value, "houseNumber");
            return (Criteria) this;
        }

        public Criteria andHouseNumberLessThan(String value) {
            addCriterion("\"HOUSE_NUMBER\" <", value, "houseNumber");
            return (Criteria) this;
        }

        public Criteria andHouseNumberLessThanOrEqualTo(String value) {
            addCriterion("\"HOUSE_NUMBER\" <=", value, "houseNumber");
            return (Criteria) this;
        }

        public Criteria andHouseNumberLike(String value) {
            addCriterion("\"HOUSE_NUMBER\" like", value, "houseNumber");
            return (Criteria) this;
        }

        public Criteria andHouseNumberNotLike(String value) {
            addCriterion("\"HOUSE_NUMBER\" not like", value, "houseNumber");
            return (Criteria) this;
        }

        public Criteria andHouseNumberIn(List<String> values) {
            addCriterion("\"HOUSE_NUMBER\" in", values, "houseNumber");
            return (Criteria) this;
        }

        public Criteria andHouseNumberNotIn(List<String> values) {
            addCriterion("\"HOUSE_NUMBER\" not in", values, "houseNumber");
            return (Criteria) this;
        }

        public Criteria andHouseNumberBetween(String value1, String value2) {
            addCriterion("\"HOUSE_NUMBER\" between", value1, value2, "houseNumber");
            return (Criteria) this;
        }

        public Criteria andHouseNumberNotBetween(String value1, String value2) {
            addCriterion("\"HOUSE_NUMBER\" not between", value1, value2, "houseNumber");
            return (Criteria) this;
        }

        public Criteria andStreetDirectionalIsNull() {
            addCriterion("\"STREET_DIRECTIONAL\" is null");
            return (Criteria) this;
        }

        public Criteria andStreetDirectionalIsNotNull() {
            addCriterion("\"STREET_DIRECTIONAL\" is not null");
            return (Criteria) this;
        }

        public Criteria andStreetDirectionalEqualTo(String value) {
            addCriterion("\"STREET_DIRECTIONAL\" =", value, "streetDirectional");
            return (Criteria) this;
        }

        public Criteria andStreetDirectionalNotEqualTo(String value) {
            addCriterion("\"STREET_DIRECTIONAL\" <>", value, "streetDirectional");
            return (Criteria) this;
        }

        public Criteria andStreetDirectionalGreaterThan(String value) {
            addCriterion("\"STREET_DIRECTIONAL\" >", value, "streetDirectional");
            return (Criteria) this;
        }

        public Criteria andStreetDirectionalGreaterThanOrEqualTo(String value) {
            addCriterion("\"STREET_DIRECTIONAL\" >=", value, "streetDirectional");
            return (Criteria) this;
        }

        public Criteria andStreetDirectionalLessThan(String value) {
            addCriterion("\"STREET_DIRECTIONAL\" <", value, "streetDirectional");
            return (Criteria) this;
        }

        public Criteria andStreetDirectionalLessThanOrEqualTo(String value) {
            addCriterion("\"STREET_DIRECTIONAL\" <=", value, "streetDirectional");
            return (Criteria) this;
        }

        public Criteria andStreetDirectionalLike(String value) {
            addCriterion("\"STREET_DIRECTIONAL\" like", value, "streetDirectional");
            return (Criteria) this;
        }

        public Criteria andStreetDirectionalNotLike(String value) {
            addCriterion("\"STREET_DIRECTIONAL\" not like", value, "streetDirectional");
            return (Criteria) this;
        }

        public Criteria andStreetDirectionalIn(List<String> values) {
            addCriterion("\"STREET_DIRECTIONAL\" in", values, "streetDirectional");
            return (Criteria) this;
        }

        public Criteria andStreetDirectionalNotIn(List<String> values) {
            addCriterion("\"STREET_DIRECTIONAL\" not in", values, "streetDirectional");
            return (Criteria) this;
        }

        public Criteria andStreetDirectionalBetween(String value1, String value2) {
            addCriterion("\"STREET_DIRECTIONAL\" between", value1, value2, "streetDirectional");
            return (Criteria) this;
        }

        public Criteria andStreetDirectionalNotBetween(String value1, String value2) {
            addCriterion("\"STREET_DIRECTIONAL\" not between", value1, value2, "streetDirectional");
            return (Criteria) this;
        }

        public Criteria andStreetSuffixIsNull() {
            addCriterion("\"STREET_SUFFIX\" is null");
            return (Criteria) this;
        }

        public Criteria andStreetSuffixIsNotNull() {
            addCriterion("\"STREET_SUFFIX\" is not null");
            return (Criteria) this;
        }

        public Criteria andStreetSuffixEqualTo(String value) {
            addCriterion("\"STREET_SUFFIX\" =", value, "streetSuffix");
            return (Criteria) this;
        }

        public Criteria andStreetSuffixNotEqualTo(String value) {
            addCriterion("\"STREET_SUFFIX\" <>", value, "streetSuffix");
            return (Criteria) this;
        }

        public Criteria andStreetSuffixGreaterThan(String value) {
            addCriterion("\"STREET_SUFFIX\" >", value, "streetSuffix");
            return (Criteria) this;
        }

        public Criteria andStreetSuffixGreaterThanOrEqualTo(String value) {
            addCriterion("\"STREET_SUFFIX\" >=", value, "streetSuffix");
            return (Criteria) this;
        }

        public Criteria andStreetSuffixLessThan(String value) {
            addCriterion("\"STREET_SUFFIX\" <", value, "streetSuffix");
            return (Criteria) this;
        }

        public Criteria andStreetSuffixLessThanOrEqualTo(String value) {
            addCriterion("\"STREET_SUFFIX\" <=", value, "streetSuffix");
            return (Criteria) this;
        }

        public Criteria andStreetSuffixLike(String value) {
            addCriterion("\"STREET_SUFFIX\" like", value, "streetSuffix");
            return (Criteria) this;
        }

        public Criteria andStreetSuffixNotLike(String value) {
            addCriterion("\"STREET_SUFFIX\" not like", value, "streetSuffix");
            return (Criteria) this;
        }

        public Criteria andStreetSuffixIn(List<String> values) {
            addCriterion("\"STREET_SUFFIX\" in", values, "streetSuffix");
            return (Criteria) this;
        }

        public Criteria andStreetSuffixNotIn(List<String> values) {
            addCriterion("\"STREET_SUFFIX\" not in", values, "streetSuffix");
            return (Criteria) this;
        }

        public Criteria andStreetSuffixBetween(String value1, String value2) {
            addCriterion("\"STREET_SUFFIX\" between", value1, value2, "streetSuffix");
            return (Criteria) this;
        }

        public Criteria andStreetSuffixNotBetween(String value1, String value2) {
            addCriterion("\"STREET_SUFFIX\" not between", value1, value2, "streetSuffix");
            return (Criteria) this;
        }

        public Criteria andStreetNameIsNull() {
            addCriterion("\"STREET_NAME\" is null");
            return (Criteria) this;
        }

        public Criteria andStreetNameIsNotNull() {
            addCriterion("\"STREET_NAME\" is not null");
            return (Criteria) this;
        }

        public Criteria andStreetNameEqualTo(String value) {
            addCriterion("\"STREET_NAME\" =", value, "streetName");
            return (Criteria) this;
        }

        public Criteria andStreetNameNotEqualTo(String value) {
            addCriterion("\"STREET_NAME\" <>", value, "streetName");
            return (Criteria) this;
        }

        public Criteria andStreetNameGreaterThan(String value) {
            addCriterion("\"STREET_NAME\" >", value, "streetName");
            return (Criteria) this;
        }

        public Criteria andStreetNameGreaterThanOrEqualTo(String value) {
            addCriterion("\"STREET_NAME\" >=", value, "streetName");
            return (Criteria) this;
        }

        public Criteria andStreetNameLessThan(String value) {
            addCriterion("\"STREET_NAME\" <", value, "streetName");
            return (Criteria) this;
        }

        public Criteria andStreetNameLessThanOrEqualTo(String value) {
            addCriterion("\"STREET_NAME\" <=", value, "streetName");
            return (Criteria) this;
        }

        public Criteria andStreetNameLike(String value) {
            addCriterion("\"STREET_NAME\" like", value, "streetName");
            return (Criteria) this;
        }

        public Criteria andStreetNameNotLike(String value) {
            addCriterion("\"STREET_NAME\" not like", value, "streetName");
            return (Criteria) this;
        }

        public Criteria andStreetNameIn(List<String> values) {
            addCriterion("\"STREET_NAME\" in", values, "streetName");
            return (Criteria) this;
        }

        public Criteria andStreetNameNotIn(List<String> values) {
            addCriterion("\"STREET_NAME\" not in", values, "streetName");
            return (Criteria) this;
        }

        public Criteria andStreetNameBetween(String value1, String value2) {
            addCriterion("\"STREET_NAME\" between", value1, value2, "streetName");
            return (Criteria) this;
        }

        public Criteria andStreetNameNotBetween(String value1, String value2) {
            addCriterion("\"STREET_NAME\" not between", value1, value2, "streetName");
            return (Criteria) this;
        }

        public Criteria andStreetTypeIsNull() {
            addCriterion("\"STREET_TYPE\" is null");
            return (Criteria) this;
        }

        public Criteria andStreetTypeIsNotNull() {
            addCriterion("\"STREET_TYPE\" is not null");
            return (Criteria) this;
        }

        public Criteria andStreetTypeEqualTo(String value) {
            addCriterion("\"STREET_TYPE\" =", value, "streetType");
            return (Criteria) this;
        }

        public Criteria andStreetTypeNotEqualTo(String value) {
            addCriterion("\"STREET_TYPE\" <>", value, "streetType");
            return (Criteria) this;
        }

        public Criteria andStreetTypeGreaterThan(String value) {
            addCriterion("\"STREET_TYPE\" >", value, "streetType");
            return (Criteria) this;
        }

        public Criteria andStreetTypeGreaterThanOrEqualTo(String value) {
            addCriterion("\"STREET_TYPE\" >=", value, "streetType");
            return (Criteria) this;
        }

        public Criteria andStreetTypeLessThan(String value) {
            addCriterion("\"STREET_TYPE\" <", value, "streetType");
            return (Criteria) this;
        }

        public Criteria andStreetTypeLessThanOrEqualTo(String value) {
            addCriterion("\"STREET_TYPE\" <=", value, "streetType");
            return (Criteria) this;
        }

        public Criteria andStreetTypeLike(String value) {
            addCriterion("\"STREET_TYPE\" like", value, "streetType");
            return (Criteria) this;
        }

        public Criteria andStreetTypeNotLike(String value) {
            addCriterion("\"STREET_TYPE\" not like", value, "streetType");
            return (Criteria) this;
        }

        public Criteria andStreetTypeIn(List<String> values) {
            addCriterion("\"STREET_TYPE\" in", values, "streetType");
            return (Criteria) this;
        }

        public Criteria andStreetTypeNotIn(List<String> values) {
            addCriterion("\"STREET_TYPE\" not in", values, "streetType");
            return (Criteria) this;
        }

        public Criteria andStreetTypeBetween(String value1, String value2) {
            addCriterion("\"STREET_TYPE\" between", value1, value2, "streetType");
            return (Criteria) this;
        }

        public Criteria andStreetTypeNotBetween(String value1, String value2) {
            addCriterion("\"STREET_TYPE\" not between", value1, value2, "streetType");
            return (Criteria) this;
        }

        public Criteria andDescriptiveLocationIsNull() {
            addCriterion("\"DESCRIPTIVE_LOCATION\" is null");
            return (Criteria) this;
        }

        public Criteria andDescriptiveLocationIsNotNull() {
            addCriterion("\"DESCRIPTIVE_LOCATION\" is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptiveLocationEqualTo(String value) {
            addCriterion("\"DESCRIPTIVE_LOCATION\" =", value, "descriptiveLocation");
            return (Criteria) this;
        }

        public Criteria andDescriptiveLocationNotEqualTo(String value) {
            addCriterion("\"DESCRIPTIVE_LOCATION\" <>", value, "descriptiveLocation");
            return (Criteria) this;
        }

        public Criteria andDescriptiveLocationGreaterThan(String value) {
            addCriterion("\"DESCRIPTIVE_LOCATION\" >", value, "descriptiveLocation");
            return (Criteria) this;
        }

        public Criteria andDescriptiveLocationGreaterThanOrEqualTo(String value) {
            addCriterion("\"DESCRIPTIVE_LOCATION\" >=", value, "descriptiveLocation");
            return (Criteria) this;
        }

        public Criteria andDescriptiveLocationLessThan(String value) {
            addCriterion("\"DESCRIPTIVE_LOCATION\" <", value, "descriptiveLocation");
            return (Criteria) this;
        }

        public Criteria andDescriptiveLocationLessThanOrEqualTo(String value) {
            addCriterion("\"DESCRIPTIVE_LOCATION\" <=", value, "descriptiveLocation");
            return (Criteria) this;
        }

        public Criteria andDescriptiveLocationLike(String value) {
            addCriterion("\"DESCRIPTIVE_LOCATION\" like", value, "descriptiveLocation");
            return (Criteria) this;
        }

        public Criteria andDescriptiveLocationNotLike(String value) {
            addCriterion("\"DESCRIPTIVE_LOCATION\" not like", value, "descriptiveLocation");
            return (Criteria) this;
        }

        public Criteria andDescriptiveLocationIn(List<String> values) {
            addCriterion("\"DESCRIPTIVE_LOCATION\" in", values, "descriptiveLocation");
            return (Criteria) this;
        }

        public Criteria andDescriptiveLocationNotIn(List<String> values) {
            addCriterion("\"DESCRIPTIVE_LOCATION\" not in", values, "descriptiveLocation");
            return (Criteria) this;
        }

        public Criteria andDescriptiveLocationBetween(String value1, String value2) {
            addCriterion("\"DESCRIPTIVE_LOCATION\" between", value1, value2, "descriptiveLocation");
            return (Criteria) this;
        }

        public Criteria andDescriptiveLocationNotBetween(String value1, String value2) {
            addCriterion("\"DESCRIPTIVE_LOCATION\" not between", value1, value2, "descriptiveLocation");
            return (Criteria) this;
        }

        public Criteria andFloorIsNull() {
            addCriterion("\"FLOOR\" is null");
            return (Criteria) this;
        }

        public Criteria andFloorIsNotNull() {
            addCriterion("\"FLOOR\" is not null");
            return (Criteria) this;
        }

        public Criteria andFloorEqualTo(String value) {
            addCriterion("\"FLOOR\" =", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorNotEqualTo(String value) {
            addCriterion("\"FLOOR\" <>", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorGreaterThan(String value) {
            addCriterion("\"FLOOR\" >", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorGreaterThanOrEqualTo(String value) {
            addCriterion("\"FLOOR\" >=", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorLessThan(String value) {
            addCriterion("\"FLOOR\" <", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorLessThanOrEqualTo(String value) {
            addCriterion("\"FLOOR\" <=", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorLike(String value) {
            addCriterion("\"FLOOR\" like", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorNotLike(String value) {
            addCriterion("\"FLOOR\" not like", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorIn(List<String> values) {
            addCriterion("\"FLOOR\" in", values, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorNotIn(List<String> values) {
            addCriterion("\"FLOOR\" not in", values, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorBetween(String value1, String value2) {
            addCriterion("\"FLOOR\" between", value1, value2, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorNotBetween(String value1, String value2) {
            addCriterion("\"FLOOR\" not between", value1, value2, "floor");
            return (Criteria) this;
        }

        public Criteria andRoomIsNull() {
            addCriterion("\"ROOM\" is null");
            return (Criteria) this;
        }

        public Criteria andRoomIsNotNull() {
            addCriterion("\"ROOM\" is not null");
            return (Criteria) this;
        }

        public Criteria andRoomEqualTo(String value) {
            addCriterion("\"ROOM\" =", value, "room");
            return (Criteria) this;
        }

        public Criteria andRoomNotEqualTo(String value) {
            addCriterion("\"ROOM\" <>", value, "room");
            return (Criteria) this;
        }

        public Criteria andRoomGreaterThan(String value) {
            addCriterion("\"ROOM\" >", value, "room");
            return (Criteria) this;
        }

        public Criteria andRoomGreaterThanOrEqualTo(String value) {
            addCriterion("\"ROOM\" >=", value, "room");
            return (Criteria) this;
        }

        public Criteria andRoomLessThan(String value) {
            addCriterion("\"ROOM\" <", value, "room");
            return (Criteria) this;
        }

        public Criteria andRoomLessThanOrEqualTo(String value) {
            addCriterion("\"ROOM\" <=", value, "room");
            return (Criteria) this;
        }

        public Criteria andRoomLike(String value) {
            addCriterion("\"ROOM\" like", value, "room");
            return (Criteria) this;
        }

        public Criteria andRoomNotLike(String value) {
            addCriterion("\"ROOM\" not like", value, "room");
            return (Criteria) this;
        }

        public Criteria andRoomIn(List<String> values) {
            addCriterion("\"ROOM\" in", values, "room");
            return (Criteria) this;
        }

        public Criteria andRoomNotIn(List<String> values) {
            addCriterion("\"ROOM\" not in", values, "room");
            return (Criteria) this;
        }

        public Criteria andRoomBetween(String value1, String value2) {
            addCriterion("\"ROOM\" between", value1, value2, "room");
            return (Criteria) this;
        }

        public Criteria andRoomNotBetween(String value1, String value2) {
            addCriterion("\"ROOM\" not between", value1, value2, "room");
            return (Criteria) this;
        }

        public Criteria andBuildingIsNull() {
            addCriterion("\"BUILDING\" is null");
            return (Criteria) this;
        }

        public Criteria andBuildingIsNotNull() {
            addCriterion("\"BUILDING\" is not null");
            return (Criteria) this;
        }

        public Criteria andBuildingEqualTo(String value) {
            addCriterion("\"BUILDING\" =", value, "building");
            return (Criteria) this;
        }

        public Criteria andBuildingNotEqualTo(String value) {
            addCriterion("\"BUILDING\" <>", value, "building");
            return (Criteria) this;
        }

        public Criteria andBuildingGreaterThan(String value) {
            addCriterion("\"BUILDING\" >", value, "building");
            return (Criteria) this;
        }

        public Criteria andBuildingGreaterThanOrEqualTo(String value) {
            addCriterion("\"BUILDING\" >=", value, "building");
            return (Criteria) this;
        }

        public Criteria andBuildingLessThan(String value) {
            addCriterion("\"BUILDING\" <", value, "building");
            return (Criteria) this;
        }

        public Criteria andBuildingLessThanOrEqualTo(String value) {
            addCriterion("\"BUILDING\" <=", value, "building");
            return (Criteria) this;
        }

        public Criteria andBuildingLike(String value) {
            addCriterion("\"BUILDING\" like", value, "building");
            return (Criteria) this;
        }

        public Criteria andBuildingNotLike(String value) {
            addCriterion("\"BUILDING\" not like", value, "building");
            return (Criteria) this;
        }

        public Criteria andBuildingIn(List<String> values) {
            addCriterion("\"BUILDING\" in", values, "building");
            return (Criteria) this;
        }

        public Criteria andBuildingNotIn(List<String> values) {
            addCriterion("\"BUILDING\" not in", values, "building");
            return (Criteria) this;
        }

        public Criteria andBuildingBetween(String value1, String value2) {
            addCriterion("\"BUILDING\" between", value1, value2, "building");
            return (Criteria) this;
        }

        public Criteria andBuildingNotBetween(String value1, String value2) {
            addCriterion("\"BUILDING\" not between", value1, value2, "building");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("\"CITY\" is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("\"CITY\" is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("\"CITY\" =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("\"CITY\" <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("\"CITY\" >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("\"CITY\" >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("\"CITY\" <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("\"CITY\" <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("\"CITY\" like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("\"CITY\" not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("\"CITY\" in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("\"CITY\" not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("\"CITY\" between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("\"CITY\" not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andProvinceStateIsNull() {
            addCriterion("\"PROVINCE_STATE\" is null");
            return (Criteria) this;
        }

        public Criteria andProvinceStateIsNotNull() {
            addCriterion("\"PROVINCE_STATE\" is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceStateEqualTo(String value) {
            addCriterion("\"PROVINCE_STATE\" =", value, "provinceState");
            return (Criteria) this;
        }

        public Criteria andProvinceStateNotEqualTo(String value) {
            addCriterion("\"PROVINCE_STATE\" <>", value, "provinceState");
            return (Criteria) this;
        }

        public Criteria andProvinceStateGreaterThan(String value) {
            addCriterion("\"PROVINCE_STATE\" >", value, "provinceState");
            return (Criteria) this;
        }

        public Criteria andProvinceStateGreaterThanOrEqualTo(String value) {
            addCriterion("\"PROVINCE_STATE\" >=", value, "provinceState");
            return (Criteria) this;
        }

        public Criteria andProvinceStateLessThan(String value) {
            addCriterion("\"PROVINCE_STATE\" <", value, "provinceState");
            return (Criteria) this;
        }

        public Criteria andProvinceStateLessThanOrEqualTo(String value) {
            addCriterion("\"PROVINCE_STATE\" <=", value, "provinceState");
            return (Criteria) this;
        }

        public Criteria andProvinceStateLike(String value) {
            addCriterion("\"PROVINCE_STATE\" like", value, "provinceState");
            return (Criteria) this;
        }

        public Criteria andProvinceStateNotLike(String value) {
            addCriterion("\"PROVINCE_STATE\" not like", value, "provinceState");
            return (Criteria) this;
        }

        public Criteria andProvinceStateIn(List<String> values) {
            addCriterion("\"PROVINCE_STATE\" in", values, "provinceState");
            return (Criteria) this;
        }

        public Criteria andProvinceStateNotIn(List<String> values) {
            addCriterion("\"PROVINCE_STATE\" not in", values, "provinceState");
            return (Criteria) this;
        }

        public Criteria andProvinceStateBetween(String value1, String value2) {
            addCriterion("\"PROVINCE_STATE\" between", value1, value2, "provinceState");
            return (Criteria) this;
        }

        public Criteria andProvinceStateNotBetween(String value1, String value2) {
            addCriterion("\"PROVINCE_STATE\" not between", value1, value2, "provinceState");
            return (Criteria) this;
        }

        public Criteria andZipCodeIsNull() {
            addCriterion("\"ZIP_CODE\" is null");
            return (Criteria) this;
        }

        public Criteria andZipCodeIsNotNull() {
            addCriterion("\"ZIP_CODE\" is not null");
            return (Criteria) this;
        }

        public Criteria andZipCodeEqualTo(String value) {
            addCriterion("\"ZIP_CODE\" =", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotEqualTo(String value) {
            addCriterion("\"ZIP_CODE\" <>", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeGreaterThan(String value) {
            addCriterion("\"ZIP_CODE\" >", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeGreaterThanOrEqualTo(String value) {
            addCriterion("\"ZIP_CODE\" >=", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeLessThan(String value) {
            addCriterion("\"ZIP_CODE\" <", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeLessThanOrEqualTo(String value) {
            addCriterion("\"ZIP_CODE\" <=", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeLike(String value) {
            addCriterion("\"ZIP_CODE\" like", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotLike(String value) {
            addCriterion("\"ZIP_CODE\" not like", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeIn(List<String> values) {
            addCriterion("\"ZIP_CODE\" in", values, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotIn(List<String> values) {
            addCriterion("\"ZIP_CODE\" not in", values, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeBetween(String value1, String value2) {
            addCriterion("\"ZIP_CODE\" between", value1, value2, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotBetween(String value1, String value2) {
            addCriterion("\"ZIP_CODE\" not between", value1, value2, "zipCode");
            return (Criteria) this;
        }

        public Criteria andCommentsIsNull() {
            addCriterion("\"COMMENTS\" is null");
            return (Criteria) this;
        }

        public Criteria andCommentsIsNotNull() {
            addCriterion("\"COMMENTS\" is not null");
            return (Criteria) this;
        }

        public Criteria andCommentsEqualTo(String value) {
            addCriterion("\"COMMENTS\" =", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotEqualTo(String value) {
            addCriterion("\"COMMENTS\" <>", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsGreaterThan(String value) {
            addCriterion("\"COMMENTS\" >", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsGreaterThanOrEqualTo(String value) {
            addCriterion("\"COMMENTS\" >=", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLessThan(String value) {
            addCriterion("\"COMMENTS\" <", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLessThanOrEqualTo(String value) {
            addCriterion("\"COMMENTS\" <=", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLike(String value) {
            addCriterion("\"COMMENTS\" like", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotLike(String value) {
            addCriterion("\"COMMENTS\" not like", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsIn(List<String> values) {
            addCriterion("\"COMMENTS\" in", values, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotIn(List<String> values) {
            addCriterion("\"COMMENTS\" not in", values, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsBetween(String value1, String value2) {
            addCriterion("\"COMMENTS\" between", value1, value2, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotBetween(String value1, String value2) {
            addCriterion("\"COMMENTS\" not between", value1, value2, "comments");
            return (Criteria) this;
        }

        public Criteria andLosingCarrierCommentsIsNull() {
            addCriterion("\"LOSING_CARRIER_COMMENTS\" is null");
            return (Criteria) this;
        }

        public Criteria andLosingCarrierCommentsIsNotNull() {
            addCriterion("\"LOSING_CARRIER_COMMENTS\" is not null");
            return (Criteria) this;
        }

        public Criteria andLosingCarrierCommentsEqualTo(String value) {
            addCriterion("\"LOSING_CARRIER_COMMENTS\" =", value, "losingCarrierComments");
            return (Criteria) this;
        }

        public Criteria andLosingCarrierCommentsNotEqualTo(String value) {
            addCriterion("\"LOSING_CARRIER_COMMENTS\" <>", value, "losingCarrierComments");
            return (Criteria) this;
        }

        public Criteria andLosingCarrierCommentsGreaterThan(String value) {
            addCriterion("\"LOSING_CARRIER_COMMENTS\" >", value, "losingCarrierComments");
            return (Criteria) this;
        }

        public Criteria andLosingCarrierCommentsGreaterThanOrEqualTo(String value) {
            addCriterion("\"LOSING_CARRIER_COMMENTS\" >=", value, "losingCarrierComments");
            return (Criteria) this;
        }

        public Criteria andLosingCarrierCommentsLessThan(String value) {
            addCriterion("\"LOSING_CARRIER_COMMENTS\" <", value, "losingCarrierComments");
            return (Criteria) this;
        }

        public Criteria andLosingCarrierCommentsLessThanOrEqualTo(String value) {
            addCriterion("\"LOSING_CARRIER_COMMENTS\" <=", value, "losingCarrierComments");
            return (Criteria) this;
        }

        public Criteria andLosingCarrierCommentsLike(String value) {
            addCriterion("\"LOSING_CARRIER_COMMENTS\" like", value, "losingCarrierComments");
            return (Criteria) this;
        }

        public Criteria andLosingCarrierCommentsNotLike(String value) {
            addCriterion("\"LOSING_CARRIER_COMMENTS\" not like", value, "losingCarrierComments");
            return (Criteria) this;
        }

        public Criteria andLosingCarrierCommentsIn(List<String> values) {
            addCriterion("\"LOSING_CARRIER_COMMENTS\" in", values, "losingCarrierComments");
            return (Criteria) this;
        }

        public Criteria andLosingCarrierCommentsNotIn(List<String> values) {
            addCriterion("\"LOSING_CARRIER_COMMENTS\" not in", values, "losingCarrierComments");
            return (Criteria) this;
        }

        public Criteria andLosingCarrierCommentsBetween(String value1, String value2) {
            addCriterion("\"LOSING_CARRIER_COMMENTS\" between", value1, value2, "losingCarrierComments");
            return (Criteria) this;
        }

        public Criteria andLosingCarrierCommentsNotBetween(String value1, String value2) {
            addCriterion("\"LOSING_CARRIER_COMMENTS\" not between", value1, value2, "losingCarrierComments");
            return (Criteria) this;
        }

        public Criteria andDefaultRoutingProifleIsNull() {
            addCriterion("\"DEFAULT_ROUTING_PROIFLE\" is null");
            return (Criteria) this;
        }

        public Criteria andDefaultRoutingProifleIsNotNull() {
            addCriterion("\"DEFAULT_ROUTING_PROIFLE\" is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultRoutingProifleEqualTo(Integer value) {
            addCriterion("\"DEFAULT_ROUTING_PROIFLE\" =", value, "defaultRoutingProifle");
            return (Criteria) this;
        }

        public Criteria andDefaultRoutingProifleNotEqualTo(Integer value) {
            addCriterion("\"DEFAULT_ROUTING_PROIFLE\" <>", value, "defaultRoutingProifle");
            return (Criteria) this;
        }

        public Criteria andDefaultRoutingProifleGreaterThan(Integer value) {
            addCriterion("\"DEFAULT_ROUTING_PROIFLE\" >", value, "defaultRoutingProifle");
            return (Criteria) this;
        }

        public Criteria andDefaultRoutingProifleGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"DEFAULT_ROUTING_PROIFLE\" >=", value, "defaultRoutingProifle");
            return (Criteria) this;
        }

        public Criteria andDefaultRoutingProifleLessThan(Integer value) {
            addCriterion("\"DEFAULT_ROUTING_PROIFLE\" <", value, "defaultRoutingProifle");
            return (Criteria) this;
        }

        public Criteria andDefaultRoutingProifleLessThanOrEqualTo(Integer value) {
            addCriterion("\"DEFAULT_ROUTING_PROIFLE\" <=", value, "defaultRoutingProifle");
            return (Criteria) this;
        }

        public Criteria andDefaultRoutingProifleIn(List<Integer> values) {
            addCriterion("\"DEFAULT_ROUTING_PROIFLE\" in", values, "defaultRoutingProifle");
            return (Criteria) this;
        }

        public Criteria andDefaultRoutingProifleNotIn(List<Integer> values) {
            addCriterion("\"DEFAULT_ROUTING_PROIFLE\" not in", values, "defaultRoutingProifle");
            return (Criteria) this;
        }

        public Criteria andDefaultRoutingProifleBetween(Integer value1, Integer value2) {
            addCriterion("\"DEFAULT_ROUTING_PROIFLE\" between", value1, value2, "defaultRoutingProifle");
            return (Criteria) this;
        }

        public Criteria andDefaultRoutingProifleNotBetween(Integer value1, Integer value2) {
            addCriterion("\"DEFAULT_ROUTING_PROIFLE\" not between", value1, value2, "defaultRoutingProifle");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("\"CREATED_BY\" is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("\"CREATED_BY\" is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("\"CREATED_BY\" =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("\"CREATED_BY\" <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("\"CREATED_BY\" >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("\"CREATED_BY\" >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("\"CREATED_BY\" <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("\"CREATED_BY\" <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("\"CREATED_BY\" like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("\"CREATED_BY\" not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("\"CREATED_BY\" in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("\"CREATED_BY\" not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("\"CREATED_BY\" between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("\"CREATED_BY\" not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedTsIsNull() {
            addCriterion("\"CREATED_TS\" is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTsIsNotNull() {
            addCriterion("\"CREATED_TS\" is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTsEqualTo(Date value) {
            addCriterion("\"CREATED_TS\" =", value, "createdTs");
            return (Criteria) this;
        }

        public Criteria andCreatedTsNotEqualTo(Date value) {
            addCriterion("\"CREATED_TS\" <>", value, "createdTs");
            return (Criteria) this;
        }

        public Criteria andCreatedTsGreaterThan(Date value) {
            addCriterion("\"CREATED_TS\" >", value, "createdTs");
            return (Criteria) this;
        }

        public Criteria andCreatedTsGreaterThanOrEqualTo(Date value) {
            addCriterion("\"CREATED_TS\" >=", value, "createdTs");
            return (Criteria) this;
        }

        public Criteria andCreatedTsLessThan(Date value) {
            addCriterion("\"CREATED_TS\" <", value, "createdTs");
            return (Criteria) this;
        }

        public Criteria andCreatedTsLessThanOrEqualTo(Date value) {
            addCriterion("\"CREATED_TS\" <=", value, "createdTs");
            return (Criteria) this;
        }

        public Criteria andCreatedTsIn(List<Date> values) {
            addCriterion("\"CREATED_TS\" in", values, "createdTs");
            return (Criteria) this;
        }

        public Criteria andCreatedTsNotIn(List<Date> values) {
            addCriterion("\"CREATED_TS\" not in", values, "createdTs");
            return (Criteria) this;
        }

        public Criteria andCreatedTsBetween(Date value1, Date value2) {
            addCriterion("\"CREATED_TS\" between", value1, value2, "createdTs");
            return (Criteria) this;
        }

        public Criteria andCreatedTsNotBetween(Date value1, Date value2) {
            addCriterion("\"CREATED_TS\" not between", value1, value2, "createdTs");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 02 17:37:37 CDT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MSUN.CREATE_PONS_REQUEST
     *
     * @mbg.generated Sat Jun 02 17:37:37 CDT 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}