package com.magicjack.webservice.iristel.domain.vo;

import java.math.BigDecimal;

public class CreatePonsRequestServiceDetailKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQ_SVS_DETAILS.ID
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQ_SVS_DETAILS.SEQ
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    private BigDecimal seq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQ_SVS_DETAILS.ID
     *
     * @return the value of MSUN.CREATE_PONS_REQ_SVS_DETAILS.ID
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQ_SVS_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public CreatePonsRequestServiceDetailKey withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQ_SVS_DETAILS.ID
     *
     * @param id the value for MSUN.CREATE_PONS_REQ_SVS_DETAILS.ID
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQ_SVS_DETAILS.SEQ
     *
     * @return the value of MSUN.CREATE_PONS_REQ_SVS_DETAILS.SEQ
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public BigDecimal getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQ_SVS_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public CreatePonsRequestServiceDetailKey withSeq(BigDecimal seq) {
        this.setSeq(seq);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQ_SVS_DETAILS.SEQ
     *
     * @param seq the value for MSUN.CREATE_PONS_REQ_SVS_DETAILS.SEQ
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public void setSeq(BigDecimal seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQ_SVS_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", seq=").append(seq);
        sb.append("]");
        return sb.toString();
    }
}