package com.magicjack.webservice.iristel.domain.vo;

public class CreatePonsRequestServiceDetail extends CreatePonsRequestServiceDetailKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQ_SVS_DETAILS.ACTIVITY
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    private String activity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQ_SVS_DETAILS.EXISTING_ACCOUNT_NUMBER
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    private String existingAccountNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQ_SVS_DETAILS.START_NUMBER
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    private String startNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUN.CREATE_PONS_REQ_SVS_DETAILS.END_NUMBER
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    private String endNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQ_SVS_DETAILS.ACTIVITY
     *
     * @return the value of MSUN.CREATE_PONS_REQ_SVS_DETAILS.ACTIVITY
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public String getActivity() {
        return activity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQ_SVS_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public CreatePonsRequestServiceDetail withActivity(String activity) {
        this.setActivity(activity);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQ_SVS_DETAILS.ACTIVITY
     *
     * @param activity the value for MSUN.CREATE_PONS_REQ_SVS_DETAILS.ACTIVITY
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public void setActivity(String activity) {
        this.activity = activity == null ? null : activity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQ_SVS_DETAILS.EXISTING_ACCOUNT_NUMBER
     *
     * @return the value of MSUN.CREATE_PONS_REQ_SVS_DETAILS.EXISTING_ACCOUNT_NUMBER
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public String getExistingAccountNumber() {
        return existingAccountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQ_SVS_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public CreatePonsRequestServiceDetail withExistingAccountNumber(String existingAccountNumber) {
        this.setExistingAccountNumber(existingAccountNumber);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQ_SVS_DETAILS.EXISTING_ACCOUNT_NUMBER
     *
     * @param existingAccountNumber the value for MSUN.CREATE_PONS_REQ_SVS_DETAILS.EXISTING_ACCOUNT_NUMBER
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public void setExistingAccountNumber(String existingAccountNumber) {
        this.existingAccountNumber = existingAccountNumber == null ? null : existingAccountNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQ_SVS_DETAILS.START_NUMBER
     *
     * @return the value of MSUN.CREATE_PONS_REQ_SVS_DETAILS.START_NUMBER
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public String getStartNumber() {
        return startNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQ_SVS_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public CreatePonsRequestServiceDetail withStartNumber(String startNumber) {
        this.setStartNumber(startNumber);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQ_SVS_DETAILS.START_NUMBER
     *
     * @param startNumber the value for MSUN.CREATE_PONS_REQ_SVS_DETAILS.START_NUMBER
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public void setStartNumber(String startNumber) {
        this.startNumber = startNumber == null ? null : startNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUN.CREATE_PONS_REQ_SVS_DETAILS.END_NUMBER
     *
     * @return the value of MSUN.CREATE_PONS_REQ_SVS_DETAILS.END_NUMBER
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public String getEndNumber() {
        return endNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQ_SVS_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public CreatePonsRequestServiceDetail withEndNumber(String endNumber) {
        this.setEndNumber(endNumber);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUN.CREATE_PONS_REQ_SVS_DETAILS.END_NUMBER
     *
     * @param endNumber the value for MSUN.CREATE_PONS_REQ_SVS_DETAILS.END_NUMBER
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    public void setEndNumber(String endNumber) {
        this.endNumber = endNumber == null ? null : endNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUN.CREATE_PONS_REQ_SVS_DETAILS
     *
     * @mbg.generated Thu May 24 14:15:07 CDT 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", activity=").append(activity);
        sb.append(", existingAccountNumber=").append(existingAccountNumber);
        sb.append(", startNumber=").append(startNumber);
        sb.append(", endNumber=").append(endNumber);
        sb.append("]");
        return sb.toString();
    }
}